apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: asus-router-exporter
  namespace: asus-monitoring
  labels:
    # Must match the kube-prometheus-stack serviceMonitorSelector label
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      interval: 60s
      scrapeTimeout: 55s
      path: /metrics
  namespaceSelector:
    matchNames:
      - asus-monitoring
  selector:
    matchLabels:
      app: asus-router-exporter
